### ISSUE TITLE
harvester don't work with ic2 crop correctly

### ISSUE THREAD

**Issue by DrummerMC** [skyboy/MineFactoryReloaded#369]
I have make two farm with an harvester and ic2 crops

the harvester harvest on my test only the sugar canes.
I have testet it with sugar canes and potatos.

**Comment by skyboy** [comment]
IC2 crops are all handled identically; if it works on one it works on all of them. Wait for the potatoes to mature.

**Comment by BDweller** [comment]
In FTB Resurrection ( MFR 2.8.0RC5-694) The harvester doesn't get the ic2crop potatos until they get to the very last stage.

The problem is that ic2crop potatos go through the normal growth and mature, but their *last* stage is poisonous potato.

So the harvester waits until they turn to poisonous potatos, which takes a while.

That also means the harvester cannot ever get normal potatoes from ic2 crops

**Comment by skyboy** [comment]
Then this is a flaw in IC2's crop system that makes automation difficult. Don't use potatoes until IC2 gets fixed.
