### ISSUE TITLE
Latest MFR and CoFHCore cause IC2 string problems

### ISSUE THREAD

**Issue by chrixian** [skyboy/MineFactoryReloaded#370]
Using:
- industrialcraft-2-2.2.668-experimental
- CoFHCore-[1.7.10]3.0.0B9-124
- MineFactoryReloaded-[1.7.10]2.8.0RC6-45

All IndustrialCraft2 strings start displaying their localization string name instead of the actual localized string. If I remove `MineFactoryReloaded-[1.7.10]2.8.0RC6-45.jar` it stops happening.

Here is an example screenshot:
![2015-02-02_12 16 08](https://cloud.githubusercontent.com/assets/463693/6007596/0ed15cb0-aae1-11e4-9e45-a82e80e86b3e.png)

**Comment by chrixian** [comment]
Oh I mention CoFHCore in the issue title because both were updated at the same time when the issue started, CoFHCore may have nothing to do with the problem.

**Comment by chrixian** [comment]
I need to investigate the cause further, it might not be MFR related after all.

**Comment by abdullamu** [comment]
i have this problem too

**Comment by chrixian** [comment]
Alright, I've done all I can to track down the cause and I'm sort of stumped so I'll reopen this issue and hope someone familiar the code might have some thoughts... 

Expanding on what I said in the first post-- The issue is happening if either MineFactoryReloaded -or- NetherOres is installed. Both of those mods require CoFHCore so I assumed it has something to do with it.. I thought maybe it was simply because both mods extend BaseMod but then I find other mods which also extend BaseMod (like Redstone Arsenal) don't cause the problem. 

100% of the IC2 strings are doing it everywhere-- in machines (see the example image on the initial post), in item tooltips, in WAILA, etc. and the only other location I find the problem is on a Tinkers Construct bow I made from MFR plastic shows up as "item.mfr.plastic Shortbow" (but the MFR plastic and rubber items are unaffected) and the modifier on some arrows I made from a blaze rod shows up as "modifier.tool.blaze" but every other item from Tinkers Construct is unaffected. 

So it's got me puzzled...  can anyone think of what MFR and NetherOres has in common that would cause an issue with localized string values of 1 entire mod and a handful of other items but not effect everything else? :confounded:

**Comment by abdullamu** [comment]
you are awesome ,all respect for u and your work i wish i can help ,but if you go back in versions and find which one works write with ic2 and than see whats the changes in the old and new build wouldnt that help ?

**Comment by Maxital** [comment]
Can confirm, i did some tests with as little mods as possible and found out it starts misbehaving with CoFHCore-[1.7.10]3.0.0B9-110
Works fine with CoFHCore-[1.7.10]3.0.0B9-109

The commit for the 3.0.0B9-110 build maybe caused by https://github.com/CoFH/CoFHCore/commit/72fa8fbd9a9487523959b7b02df98fb4d280629e
or something around that same timeline.

Mods i tested with:
forge-1.7.10-10.13.2.1291
1.7.10\CodeChickenLib-1.7.10-1.1.1.110-universal.jar
1.7.10\ForgeMultipart-1.7.10-1.1.1.320-universal.jar
ic2\ejml-0.23.jar
CodeChickenCore-1.7.10-1.0.4.35-universal.jar
CoFHCore-[1.7.10]3.0.0B9-109.jar
CoFHLib-[1.7.10]1.0.0B9-85.jar
industrialcraft-2-2.2.671-experimental.jar
MineFactoryReloaded-[1.7.10]2.8.0RC6-47.jar
NotEnoughItems-1.7.10-1.0.4.83-universal.jar
RedstoneArsenal-[1.7.10]1.1.0RC1-33.jar
ThermalExpansion-[1.7.10]4.0.0B8-23.jar
ThermalFoundation-[1.7.10]1.0.0RC1-35.jar

Java: jdk-8u31

/Max

**Comment by abdullamu** [comment]
i would want to downgrade but im worried that it might break my world since i dont know the changelog for any of cofh or mfr , why they dont release changelog i searched everywhere but never found it ?

**Comment by Maxital** [comment]
You can basically read the changelog as they commit -> https://github.com/CoFH/CoFHCore/commits/master

But wait they will most likely fix this asap :) and you can download the jar file from curse

I also posted the report here https://github.com/CoFH/Feedback/issues/83 as its more related to CoFHCore il guess.

/Max

**Comment by skyboy** [comment]
See the referenced issue for updates.
