### ISSUE TITLE
Sludge boiler produces 2 non-stackable types of dirt blocks

### ISSUE THREAD

**Issue by enkryptor** [skyboy/MineFactoryReloaded#371]
The setup:
sludge boiler
a conveyor belt beneath it
an item collector
a vanilla chest

After a couple of boiling cycles I find two different types of dirt blocks in the chest. You cannot stack it until you place it in the world and break.

The boiler is powered up with a leadstone energy cell from TE. Other blocks it produces (sand, clay, etc.) stack without issues.

**Comment by skyboy** [comment]
The most common type of dirt is "coarse dirt" in 1.8 (in 1.7 it has the same name and texture), and grass cannot grow on it. The less common type is regular dirt.

This is normal, and intentional, behavior; however, mojang's decision to have it use the same name and texture is confusing and I can't do anything about that.

**Comment by enkryptor** [comment]
I think, the boiler shouldn't produce this type of block in 1.7.

When you break this coarse dirt block, you get a simple dirt block, don't you?

**Comment by skyboy** [comment]
You do, and that's not in my control.

**Comment by enkryptor** [comment]
doesn't that mean the Boiler should not produce this block at all?..
