### ISSUE TITLE
Chunk Loader strangeness

### ISSUE THREAD

**Issue by tgstyle** [skyboy/MineFactoryReloaded#430]
I am using a chunk loader in Aroma's Dimensional World mod (mining world). It is powered via a dimensional transceiver from EnderIO. The odd thing is, unless it is actively charging, it will not keep the area chunk loaded in the mining world dimension (2). I am watching the server and it is not saying anything about unloading the dimension either. 

Using latest release 2.8.0-104
Forge 1.7.10 1352

**Comment by tgstyle** [comment]
Note it works fine in the overworld, I will test other dimensions to see if I have the same results.

**Comment by tgstyle** [comment]
I have tracked it down to the chunk loader not loading all chunks when it is set to 2. It appears to do a 3x3 grid instead of a 5x5 grid. I have seen it do this in the Mining World and in the Deep Dark dimentions. The overworld seems to be working fine.

**Comment by skyboy** [comment]
The area loaded by the chunk loader is a circular area, not a square area. The limit of 2 is due to your forgeChunkLoading.cfg having the default limits for player tickets: 500 tickets at a max of 25 chunks each. I recommend more around 10 tickets at 1250 chunks each (same total number of chunks: fewer permitted chunk loaders per-player, though). Alternatively, there's a config option in MFR's common.cfg to ignore the per-ticket limit entirely.
