### ISSUE TITLE
Problrm with thaumcraft

### ISSUE THREAD

**Issue by Neuromantix** [skyboy/MineFactoryReloaded#492]
Part of log http://pastebin.com/CMv3BnQA
Problem wuith thaum/mfr compat

**Comment by skyboy** [comment]
This has been reported several times before, and there is nothing that can be done about it on MFR's end. It's caused by another mod making thaumcraft enter a loop when adding aspects to MFR's items.

Many of the other issues have been linked through https://github.com/skyboy/MineFactoryReloaded/issues/446
