### ISSUE TITLE
ArrayIndexOutOfBounds when digging

### ISSUE THREAD

**Issue by SvEgiiVEteR** [skyboy/MineFactoryReloaded#551]
MineFactoryReloaded-[1.7.10]2.8.1-174-R.jar
crash occurs sometimes immediately, sometimes after 5 minutes. just breaks ground or ore in  creativity.
I no it does not find what the problem is((((
 tell me what is the reason 
https://gist.github.com/cbfd8c2d604d3916420c15029427a2c6

**Comment by skyboy** [comment]
What's happened here is either that another mod has spawned some of MFR's blocks indiscriminately, creating things it should not, you have an invalid ore generation config via a mod like CoFHCore, or your world had at some point experienced corruption and some ores were transformed into MFR blocks.
Regardless of the specific details, this differs from https://github.com/skyboy/MineFactoryReloaded/issues/547 in that it is not a recurring issue caused by the block in question being a leaf and has another mod consistently mess it up. If it were, I would expect a small flood of issues relating to it.
