### ISSUE TITLE
PRC doesn't accept or emit signals

### ISSUE THREAD

**Issue by ouroborus** [skyboy/MineFactoryReloaded#671]
I've tried a number of configurations. Rednet wire seems to work fine but the PRC doesn't seem to accept or emit any signals.

All The Mods 1 v3.02
MineFactory Reloaded 2.9.0B1

**Comment by planetWayne** [comment]
Thought I was going loopy with this - glad I found this post.
This was part of the FoolCraft2 mudpack - which has version 2.9.0B1.

Created a real simple PRC layout. 7 segment display out of the top of a PRC and two buttons on two separate colour channels on a piece of rednet to the left. Each button was the input to a counter's Inc or Dec input. The output from the counter feeding the input of the 7 segment display.

Clicking each button, does nothing to the 7 segment display / counter. using the rednet meter shows that the channel accepts the change due to the button press, but the controller appears to do nothing with it. 

If I add a square wave counter to the circuit and stick its output to be the input to the counter, then the counter increases and the 7 segment displays the number as expected.

Hope this helps.
