### ISSUE TITLE
[1.10.2] Auto-Brewer not working properly (I think)

### ISSUE THREAD

**Issue by twsx** [skyboy/MineFactoryReloaded#676]
I've talked to several people on Discords about it, and nobody seems to know what it is about. Yet still, if I'm just doing it wrong, I apologize.

The Auto-Brewer doesn't seem to work at all at present.
Adding Ingredients to the middle column shows a big red zero, bottles do not fill with water, and even if already filled bottles are put in, it doesn't craft anything.

Here's a picture to illustrate what I mean: https://imgur.com/Hs1r4Ov

* Machine is not receiving a redstone signal; Idle bar keeps spamming through
* Shift-clicking resources from the inventory does NOT add them to the row of the appropriate counterpart, as it used to do.
* I've tried all manner of clicking and keyboard combination when trying to add a ressource to the middle column, to no avail.

Again, I hope this is not PEBKAC, but it seemed impossible to get it to work.

Version used is 2.9.0B1

**Comment by ReiDaTecnologia** [comment]
I already saw this red 0 in the items, when try automate IndustrialCraft machines using anothers mod many times have this problem and the items used is lost because they become invalid/null. This is a really f annoying incompatibility problem or glitch/error, but this is expected when a mod is in alpha.

**Comment by MuhsinunCool** [comment]
Bump. I'm having the same issue. Please fix :(
